name = "iguelph"
type = "javascript"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[build]
command = "npm run build"
cwd = "./"

# Serve static assets from the dist directory
assets = { directory = "dist/igem_guelph_website/browser" }

[[routes]]
pattern = "igemguelph.org/*"
zone_name = "igemguelph.org"

[[routes]]
pattern = "www.igemguelph.org/*"
zone_name = "igemguelph.org"

workers_dev = true